#!/usr/bin/env python3
"""Select public metadata only; no patches, tests, model calls, or image downloads."""
import argparse,collections,hashlib,json,math
from pathlib import Path
import pyarrow.parquet as pq
P=Path(__file__).resolve().parent.parent
p=argparse.ArgumentParser(description=__doc__);p.add_argument('--dataset',type=Path,required=True);p.add_argument('--output',type=Path,required=True);a=p.parse_args()
if a.output.exists():p.error('Preserve the previous specification')
sha=lambda f:hashlib.sha256(f.read_bytes()).hexdigest()
oldpath=P/'docs/evidence/proposed-task-manifest-20261003.json';old=json.loads(oldpath.read_text());assert sha(a.dataset)==old['datasetSha256']
seen={c['instanceId'] for k in ['prefix','heldOut'] for c in old[k]}|set(old['excludedDebugInstances'])
continuous=P/'docs/continuous-learning-protocol-20261004.md'
seen|={'django__django-'+str(n) for n in [11848,11551,12262,11815,11880,11790,11999,11740]}
assert len(seen)==34
columns=['instance_id','repo','version','created_at','base_commit']
rows=pq.read_table(a.dataset,columns=columns).to_pylist();remaining=[r for r in rows if r['instance_id'] not in seen]
candidates=sorted([r for r in remaining if r['repo']=='django/django' and tuple(int(v) for v in r['version'].split('.'))>=(3,0)],key=lambda r:(r['created_at'],r['instance_id']))
assert len(candidates)>=104
case=lambda r:dict(instanceId=r['instance_id'],baseCommit=r['base_commit'],createdAt=r['created_at'],version=r['version'],repo=r['repo'])
selected=candidates[:104];manifest={'prefix':[case(r) for r in selected[:4]],'heldOut':[case(r) for r in selected[4:]],'datasetSha256':sha(a.dataset)}
spec={'status':'PROPOSED_SWE_EXPANSION_NOT_FROZEN','model':'qwen3.8-27b','thinking':'off','workers':2,'datasetSha256':sha(a.dataset),'manifest':manifest,'budgets':{'foregroundCalls':40,'wallSeconds':1200,'prefixBackgroundCalls':100,'heldOutBackgroundCalls':10,'prefixSettleSeconds':180,'finalPrefixSettleSeconds':360,'heldOutSettleSeconds':180},'selection':'Django version >=3.0; exclude 34 exposed tasks; sort created_at then instance_id; first 4 prefix and next 100 evaluation. Public metadata only, no outcome selection.','excluded':sorted(seen),'exposureEvidence':{str(f.relative_to(P)):sha(f) for f in [oldpath,continuous]},'inventory':{'datasetTasks':len(rows),'unexposedAllRepos':len(remaining),'unexposedDjango':sum(r['repo']=='django/django' for r in remaining),'eligibleDjangoVersion3Plus':len(candidates),'eligibleVersionCounts':dict(sorted(collections.Counter(r['version'] for r in candidates).items())),'selectedVersionCounts':dict(sorted(collections.Counter(r['version'] for r in selected).items()))},'historyPolicy':'Both arms retain their own four prefix task logs. RSI additionally retains natural native assets. Each held-out case gets an independent copy of its arm fixed prefix snapshot; held-out learning never reaches another held-out case.','effectScope':'Current-version fixed-prefix transfer in 100 Django tasks; not within-sequence continuous learning or a claim about all SWE-bench repositories.','stoppingRule':'Fixed 100 evaluation pairs, no early success/significance stopping, no automatic retries. Stop new dispatch on infrastructure, unknown usage or input failures; preserve in-flight evidence.','analysis':{'primary':'Official resolved, paired net difference and 95% paired task bootstrap interval; conditional on these four prefix tasks, code and single model run.','secondary':['full-chain known input/output tokens and unknown usage, including background and all failures','tokens per solved task','actual memory and Skill body delivery, IDs, versions and source evidence','stop reasons and task failure vs infrastructure','fixed diagnostic sample relevance, length, earliest effective recorded edit and repeated checks'],'precisionIllustration':{'formula':'Approximate 95% half-width 1.96*sqrt(q/n), near zero difference; q is discordant-pair fraction, assumptions only.','n':100,'halfWidthAtQ020':1.96*math.sqrt(.2/100),'halfWidthAtQ040':1.96*math.sqrt(.4/100),'notPowerGuarantee':True}},'costPlanning':'Old runs suggest roughly 120M-160M chat tokens for this scale; an estimate, not an exact price or token cap. Dispatch caps are hard limits. Local embedding token usage may remain unavailable.','realModelRequests':0}
a.output.parent.mkdir(parents=True,exist_ok=True);a.output.write_text(json.dumps(spec,ensure_ascii=False,indent=2)+'\n');print(json.dumps({'status':spec['status'],'prefix':4,'heldOut':100,'inventory':spec['inventory'],'realModelRequests':0},ensure_ascii=False))
