import React,{useEffect,useState} from 'react';
import {AssetSplitLayout,AssetListPanel,AssetItemHeader,AssetItemName,AssetItemDesc,AssetItemMeta,AssetItemTime,MarkdownView,FileTreeView,buildFileTree} from './hub.js';
export const scopeLabel=(scope:string)=>scope==='global'?'通用资产':'工作区资产';
export const stamp=(value:any)=>value?new Date(value).toLocaleString('zh-CN',{month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit'}):'未记录时间';
export function Icon({name,size=18}:any){const paths:any={memory:'M4 5h16v14H4z M8 2v6 M16 2v6 M8 12h8 M8 16h5',skill:'m12 3 8 4v10l-8 4-8-4V7z M4 7l8 4 8-4 M12 11v10',search:'M10.5 3a7.5 7.5 0 1 0 0 15 7.5 7.5 0 0 0 0-15 M16 16l5 5',file:'M6 3h8l4 4v14H6z M14 3v5h5 M9 12h6 M9 16h6',chevron:'m9 5 7 7-7 7',globe:'M21 12a9 9 0 1 1-18 0 9 9 0 0 1 18 0 M3 12h18 M12 3c-5 5-5 13 0 18 M12 3c5 5 5 13 0 18',folder:'M3 7V5h7l2 2h9v13H3z',clock:'M21 12a9 9 0 1 1-18 0 9 9 0 0 1 18 0 M12 7v6l4 2',more:'M5 12h.01 M12 12h.01 M19 12h.01',refresh:'M20 7V3l-4 1 M20 7a9 9 0 1 0 1 9',check:'m5 12 4 4L19 6'};return <svg aria-hidden="true" width={size} height={size} viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth={1.6} strokeLinecap="round" strokeLinejoin="round"><path d={paths[name]??paths.file}/></svg>;}
export function Markdown({children}:any){return <MarkdownView bare className="rsi-prose">{children??''}</MarkdownView>;}
export function Empty({title='暂无资产',children}:any){return <div className="rsi-empty"><Icon name="folder" size={30}/><strong>{title}</strong><p>{children}</p></div>;}
export function Search({value,onChange,label}:any){return <div className="rsi-search"><Icon name="search" size={16}/><input aria-label={label} placeholder={label} value={value} onChange={e=>onChange(e.target.value)}/>{value&&<button aria-label="清除搜索" onClick={()=>onChange('')}>×</button>}</div>;}
export function Menu({label='更多操作',children}:any){return <details className="rsi-menu"><summary aria-label={label}><Icon name="more"/></summary><div className="rsi-menu-items" onClick={e=>{const details=e.currentTarget.closest('details');if(details)details.open=false;}}>{children}</div></details>;}
const layerNames:any={L0:'原始对话',L1:'原子记忆',L2:'场景记忆',L3:'用户画像'};
const layerHints:any={L0:'保留的对话消息，可回看经验的来源。',L1:'从任务中提炼的事实、约定与经验。',L2:'围绕同一场景组织的长期经验。',L3:'根据积累的经验整理的用户画像。'};
export function MemoryAssets({data,act,busy,open}:any){
 const [scope,setScope]=useState(data.workspace.id),[layer,setLayer]=useState('L1'),[query,setQuery]=useState(''),[page,setPage]=useState(0),[result,setResult]=useState<any>(),[loading,setLoading]=useState(false),[error,setError]=useState(''),[revision,setRevision]=useState(0);
 useEffect(()=>{setScope(data.workspace.id);setPage(0);setQuery('');},[data.workspace.id]);
 const count=data.layers?.[scope]?.[layer]??0;
 useEffect(()=>{let alive=true;setResult(undefined);setError('');if(layer==='L1')return;setLoading(true);act('memoryLayer',{scope,layer,offset:page*50}).then((value:any)=>{if(alive)setResult({...value,scope,layer,page});}).catch((e:any)=>{if(alive)setError(e.message);}).finally(()=>{if(alive)setLoading(false);});return()=>{alive=false;};},[scope,layer,page,revision,count]);
 const visibleResult=result?.scope===scope&&result?.layer===layer&&result?.page===page?result:undefined;
 const all=layer==='L1'?data.memory.filter((row:any)=>row.scope===scope):visibleResult?.items??[],rows=all.filter((row:any)=>JSON.stringify(row).toLowerCase().includes(query.toLowerCase()));
 const switchLayer=(next:string)=>{setLayer(next);setQuery('');setPage(0);};
 return <AssetSplitLayout storageKey="dsh-rsi.memory.sidebar" sidebar={<AssetListPanel title="记忆范围" count={2} items={[data.workspace.id,'global']} selectedId={scope} getItemId={(id:string)=>id} onSelect={(id:string)=>{setScope(id);setPage(0);setQuery('');}} renderItem={(id:string)=>{const counts=data.layers?.[id]??{};return <><AssetItemHeader><Icon name={id==='global'?'globe':'folder'}/><AssetItemName>{scopeLabel(id)}</AssetItemName></AssetItemHeader><AssetItemDesc>{id==='global'?'跨工作区复用的偏好与经验':data.workspace.cwd.split('/').pop()}</AssetItemDesc><div className="rsi-layer-counts">{Object.keys(layerNames).map(l=><span key={l}>{l}<b>{counts[l]??0}</b></span>)}</div></>;}}/>} detail={
 <section className="rsi-asset-detail"><div className="rsi-detail-header"><div><div className="rsi-eyebrow">CHAT MEMORY</div><h3>{scopeLabel(scope)}</h3><p>{scope==='global'?'在各工作区中共享使用':data.workspace.cwd}</p></div><button className="rsi-action rsi-icon-button" aria-label="刷新记忆" disabled={busy} onClick={()=>void act('snapshot').then(()=>setRevision(v=>v+1)).catch(()=>{})}><Icon name="refresh"/></button></div>
 <div className="rsi-layer-tabs" role="tablist" aria-label="记忆层级">{Object.entries(layerNames).map(([id,label])=><button key={id} role="tab" aria-selected={layer===id} onClick={()=>switchLayer(id)}><span className={`rsi-layer-badge ${id}`}>{id}</span>{label as string}<span className="rsi-muted">{data.layers?.[scope]?.[id]??0}</span></button>)}</div>
 <div className="rsi-detail-tools"><Search label={layer==='L0'?'筛选本页对话':'搜索当前层级'} value={query} onChange={setQuery}/><span className="rsi-muted">{layerHints[layer]}</span></div>
 {data.profilePending&&['L2','L3'].includes(layer)&&<div className="rsi-notice">这些派生内容待重建，暂不参与召回。<button disabled={busy||data.settings.learningEnabled} onClick={()=>void act('rebuildProfile',{scope}).then(()=>setRevision(v=>v+1)).catch(()=>{})}>重建</button></div>}
 <div className="rsi-scroll rsi-memory-body">{error&&<p role="alert" className="rsi-error">{error}</p>}{layer!=='L1'&&!visibleResult&&!error?<Empty title="正在读取记忆"/>:!rows.length?<Empty title={query?'没有匹配的内容':`暂无${layerNames[layer]}`}>{layer==='L0'?'完成任务后，捕获的对话将显示在这里。':'随着任务积累，这里会逐步形成可复用的经验。'}</Empty>:layer==='L0'?<div className="rsi-conversation">{[...rows].reverse().map((row:any)=><article key={row.record_id} className={`rsi-message ${row.role==='user'?'is-user':''}`}><div className="rsi-message-meta">{row.role==='user'?'你':'助手'}<time>{stamp(row.timestamp)}</time><code title={row.session_id}>{row.session_id}</code></div><div className="rsi-message-bubble"><Markdown>{row.message_text}</Markdown></div></article>)}</div>:layer==='L1'?rows.map((row:any)=><article className="rsi-memory-card" key={row.id}><div className="rsi-line"><div className="rsi-memory-title"><span className="rsi-layer-badge L1">L1</span><strong>{row.scene_name||'任务经验'}</strong><span className="rsi-chip">{({instruction:'约定',fact:'事实',experience:'经验',persona:'偏好'} as any)[row.type]??row.type}</span></div><Menu label="记忆操作"><button onClick={()=>open({kind:'memory',row,content:row.content})}>纠正记忆</button><button onClick={()=>open({kind:'convertMemory',row})}>转换语言</button><button className="rsi-danger" onClick={()=>open({kind:'delete',row})}>删除记忆</button></Menu></div><Markdown>{row.content}</Markdown><footer><Icon name="clock" size={13}/>{stamp(row.updatedAt||row.createdAt)}<span>·</span><span title={row.sessionId}>来源 {row.sessionId||row.sessionKey||'未记录'}</span></footer></article>):layer==='L2'?rows.map((row:any)=><details className="rsi-scene" key={row.filename} open><summary><span className="rsi-layer-badge L2">L2</span><strong>{row.filename.replace(/\.md$/,'')}</strong><span className="rsi-muted">{row.summary}</span><Icon name="chevron" size={14}/></summary><Markdown>{row.content}</Markdown><footer className="rsi-muted">更新 {stamp(row.updated)} · 累积热度 {row.heat}</footer></details>):rows.map((row:any)=><article className="rsi-persona" key={row.id}><div className="rsi-persona-heading"><span className="rsi-layer-badge L3">L3</span><strong>用户画像</strong><span className="rsi-muted">从记忆中整理</span></div><Markdown>{row.content}</Markdown></article>)}</div>
 {layer==='L0'&&visibleResult&&<footer className="rsi-detail-footer rsi-line"><span className="rsi-muted">共 {visibleResult.total} 条 · 每页 50 条{query?' · 搜索仅筛选本页':''}</span><div><button className="rsi-action" disabled={page===0||loading} onClick={()=>setPage(p=>p-1)}>上一页</button> <button className="rsi-action" disabled={(page+1)*50>=visibleResult.total||loading} onClick={()=>setPage(p=>p+1)}>下一页</button></div></footer>}
 </section>}/>;
}
export function SkillAssets({data,act,busy,open,onImport,perform}:any){
 const [scope,setScope]=useState('all'),[query,setQuery]=useState(''),[selected,setSelected]=useState(''),[loadedDetail,setDetail]=useState<any>(),[error,setError]=useState(''),[editing,setEditing]=useState(false),[draft,setDraft]=useState(''),[file,setFile]=useState<any>(),[opening,setOpening]=useState('');
 const key=(row:any)=>`${row.scope}:${row.skill_id}`;
 const rows=data.skills.filter((row:any)=>(scope==='all'||row.scope===scope)&&`${row.visibleName} ${row.description}`.toLowerCase().includes(query.toLowerCase()));
 const current=rows.find((row:any)=>key(row)===selected)??rows[0];
 const detail=loadedDetail?.skill_id===current?.skill_id&&loadedDetail?.rsiScope===current?.scope?loadedDetail:undefined;
 // Cancel stale detail responses so a previous selection cannot overwrite the new one.
 useEffect(()=>{let alive=true;setDetail(undefined);setEditing(false);setError('');setFile(undefined);if(current)act('skill',{scope:current.scope,id:current.skill_id}).then((value:any)=>{if(alive)setDetail({...value,rsiScope:current.scope});}).catch((e:any)=>{if(alive)setError(e.message);});return()=>{alive=false;};},[current?.scope,current?.skill_id,current?.version]);
 const showVersions=()=>void act('versions',{scope:current.scope,id:current.skill_id}).then((versions:any)=>open({kind:'versions',skill:current,versions})).catch(()=>{});
 async function save(){try{await act('editSkill',{scope:current.scope,id:current.skill_id,expectedVersion:detail.version,content:draft});setEditing(false);}catch{}}
 async function preview(path:string){setOpening(path);try{const value=await act('skillFile',{scope:current.scope,id:current.skill_id,version:detail.version,path});if(value.encoding==='base64'){try{const bytes=Uint8Array.from(atob(value.content),(c:string)=>c.charCodeAt(0)),content=new TextDecoder('utf-8',{fatal:true}).decode(bytes);setFile({...value,content:content.includes('\u0000')?'':content,binary:content.includes('\u0000')});}catch{setFile({...value,content:'',binary:true});}}else setFile(value);}catch(e:any){setError(e.message);}finally{setOpening('');}}
 return <><AssetSplitLayout storageKey="dsh-rsi.skills.sidebar" sidebar={<div className="rsi-hub-sidebar"><div className="rsi-sidebar-controls"><Search label="搜索技能" value={query} onChange={setQuery}/><div className="rsi-segment" aria-label="技能范围">{[['all','全部'],[data.workspace.id,'工作区'],['global','通用']].map(([id,label])=><button key={id} aria-pressed={scope===id} onClick={()=>setScope(id)}>{label}</button>)}</div></div><AssetListPanel title="自进化技能" count={rows.length} items={rows} selectedId={current?key(current):undefined} getItemId={key} onSelect={(row:any)=>setSelected(key(row))} emptyText={query?'没有匹配的技能':'暂无技能'} renderItem={(row:any)=><><AssetItemHeader><Icon name="skill"/><AssetItemName title={row.visibleName}>{row.visibleName}</AssetItemName><span className="rsi-version">v{row.version}</span></AssetItemHeader><AssetItemDesc>{row.description}</AssetItemDesc><AssetItemMeta><span>{row.scope==='global'?'通用':'工作区'}</span><span className={row.disabled?'':'rsi-live'}>{row.disabled?'已禁用':'可使用'}</span><AssetItemTime>{stamp(row.updated_at_ms)}</AssetItemTime></AssetItemMeta></>}/><div className="rsi-sidebar-footer"><button className="rsi-action" disabled={busy} onClick={onImport}>＋ 复制已有技能</button></div></div>} detail={
 <section className="rsi-asset-detail">{!current?<Empty title="从一次任务开始积累技能">完成任务后可自动提炼，也可以复制已有技能作为起点。</Empty>:<><header className="rsi-detail-header"><div><div className="rsi-eyebrow">SKILL</div><div className="rsi-title-row"><h3>{current.visibleName}</h3><span className="rsi-version">v{current.version}</span><span className={`rsi-chip ${current.disabled?'':'rsi-live'}`}>{current.disabled?'已禁用':'可使用'}</span></div><p>{current.description}</p></div><div className="rsi-actions"><button className="rsi-action" disabled={busy||!detail} onClick={showVersions}><Icon name="clock" size={15}/>版本历史</button><Menu><button disabled={!detail} onClick={()=>{setDraft(detail.content);setEditing(true);}}>编辑 SKILL.md</button><button onClick={()=>perform('disable',{scope:current.scope,id:current.skill_id,disabled:!current.disabled})}>{current.disabled?'启用技能':'禁用技能'}</button><button onClick={()=>open({kind:'convertSkill',row:current})}>转换语言</button>{current.scope!=='global'&&<button onClick={()=>open({kind:'promote',row:current})}>复制为通用技能</button>}</Menu></div></header>
 <div className="rsi-skill-properties"><span><Icon name={current.scope==='global'?'globe':'folder'} size={14}/>{scopeLabel(current.scope)}</span><span><Icon name="clock" size={14}/>更新 {stamp(detail?.updated_at_ms)}</span><code title={current.skill_id}>{current.skill_id}</code></div>
 <div className="rsi-scroll rsi-skill-body">{error&&<div className="rsi-error" role="alert">{error}</div>}{!detail?<Empty title="正在读取技能"/>:editing?<div className="rsi-editor"><div className="rsi-line"><strong>编辑 SKILL.md</strong><span className="rsi-muted">保存为新版本</span></div><textarea aria-label="技能正文" value={draft} onChange={e=>setDraft(e.target.value)}/><p className="rsi-muted">包含 YAML 头部。若后台生成了新版本，保存会提示冲突。</p><div className="rsi-actions"><button className="rsi-action rsi-primary" disabled={busy} onClick={()=>void save()}>保存新版本</button><button className="rsi-action" disabled={busy} onClick={()=>setEditing(false)}>取消</button></div></div>:<><div className="rsi-body-label"><Icon name="file" size={15}/><span>SKILL.md</span><button className="rsi-text-button" onClick={()=>{setDraft(detail.content);setEditing(true);}}>编辑正文</button></div><Markdown>{detail.content.replace(/^---\r?\n[\s\S]*?\r?\n---(?:\r?\n|$)/,'').trim()}</Markdown></>}</div>
 <footer className="rsi-detail-footer rsi-resources"><div className="rsi-line"><strong>附属资源 <span className="rsi-count">{detail?.manifest?.length??0}</span></strong><span className="rsi-muted">只读预览</span></div>{detail?.manifest?.length?<div className="rsi-file-tree" aria-busy={!!opening}><FileTreeView nodes={buildFileTree(detail.manifest.map((item:any)=>item.path))} onPick={(path:string)=>{if(!opening)void preview(path);}}/></div>:<p className="rsi-muted">此技能没有附属资源文件。</p>}</footer></>}
 </section>}/>{file&&<div className="rsi-modal" role="dialog" aria-modal="true" aria-label="资源预览"><section className="rsi-dialog"><div className="rsi-line"><h3>{file.path}</h3><button className="rsi-action" onClick={()=>setFile(undefined)}>关闭</button></div><p className="rsi-muted">v{file.version} · {file.size_bytes} 字节</p>{file.binary?<Empty title="二进制资源">请导出资产后使用对应应用查看。</Empty>:<pre className="rsi-code-view">{file.content}</pre>}</section></div>}</>;
}
