import React,{useEffect,useRef,useState} from 'react';
import {remoteContribution,clientRequest} from '../rpc-contract.js';
export const inject=['slots','locale','remote'];
import {css,hostCss} from './styles.js';
import {AssetPageHeader,hubCss} from './hub.js';
import {MemoryAssets,SkillAssets,Icon,Markdown} from './assets.js';
const labels:any={completed:'已完成',pending:'待学习',running:'学习中',paused:'已暂停',failed:'失败',interrupted:'待恢复'};
function changed(before:string,after:string){const a=before.split('\n'),b=after.split('\n');let start=0,end=0;while(start<a.length&&start<b.length&&a[start]===b[start])start++;while(end<a.length-start&&end<b.length-start&&a[a.length-1-end]===b[b.length-1-end])end++;return [...a.slice(start,a.length-end).map(line=>'- '+line),...b.slice(start,b.length-end).map(line=>'+ '+line)].join('\n')||'正文未变化';}
function Panel({ctx}:any) {
  const [cwd,setCwd]=useState(''),[data,setData]=useState<any>(),[tab,setTab]=useState('概览'),[error,setError]=useState(''),[busy,setBusy]=useState(false),[draft,setDraft]=useState<any>(),[dialog,setDialog]=useState<any>(),[originals,setOriginals]=useState<any[]>([]);
  const mounted=useRef(false),generation=useRef(0),selected=useRef('');selected.current=cwd;
  async function fetchSnapshot(path:string) {
    const revision=++generation.current;
    try{const value=await clientRequest(ctx,'snapshot',path?{cwd:path}:{});if(mounted.current&&revision===generation.current){setData(value);if(!selected.current)setCwd(value.workspace.cwd);}}
    catch(e:any){if(mounted.current&&revision===generation.current)setError(e.message ?? String(e));}
    finally{}
  }
  useEffect(()=>{mounted.current=true;void fetchSnapshot(selected.current);const timer=setInterval(()=>{void fetchSnapshot(selected.current);},3000);return()=>{mounted.current=false;generation.current++;clearInterval(timer);};},[]);
  useEffect(()=>{generation.current++;void fetchSnapshot(cwd);},[cwd]);
  async function act(operation:string,payload:any={}) {
    const mutation=!['snapshot','memoryLayer','skill','skillFile','versions','originalSkills','searchConversations'].includes(operation);if(mutation)setBusy(true);setError('');
    try{const result=await clientRequest(ctx,operation,{cwd,...payload});if(!mounted.current)return result;if(result?.workspace)setData(result);else if(['learn'].includes(operation))await fetchSnapshot(cwd);return result;}
    catch(e:any){if(mounted.current)setError(e.message ?? String(e));throw e;}
    finally{if(mounted.current&&mutation)setBusy(false);}
  }
  const perform=(operation:string,payload:any={})=>{void act(operation,payload).catch(()=>{});};
  const download=async(scope:string)=>{try{const value=await act('export',{scope});const url=URL.createObjectURL(new Blob([JSON.stringify(value,null,2)],{type:'application/json'}));const anchor=document.createElement('a');anchor.href=url;anchor.download=`dsh-rsi-${scope}.json`;anchor.click();URL.revokeObjectURL(url);}catch{}};
  if(!data)return <section className="rsi-panel"><style>{hubCss+css+hostCss}</style><h2>自进化</h2><p>{error||'正在读取本地资产…'}</p></section>;
  const settings=draft??data.settings;
  return <section className="rsi-panel"><style>{hubCss+css+hostCss}</style>
    <AssetPageHeader title="自进化" subtitle="从任务中积累经验，让后续任务使用它。" scope={<div className="rsi-workspace"><Icon name="folder" size={15}/><span>工作区</span><select aria-label="工作区" value={cwd} onChange={e=>{setCwd(e.target.value);setData(undefined);setDialog(undefined);setDraft(undefined);}}>{[...new Set([data.workspace.cwd,...data.workspaces])].map((path:any)=><option key={path} value={path}>{path}</option>)}</select></div>}/>
    <nav className="rsi-nav" role="tablist">{['概览','记忆','技能','设置'].map(name=><button role="tab" aria-selected={tab===name} key={name} onClick={()=>{setTab(name);setDialog(undefined);}}><Icon name={name==='记忆'?'memory':name==='技能'?'skill':name==='概览'?'clock':'folder'} size={16}/>{name}</button>)}</nav>
    {error&&<div className="rsi-error" role="alert">{error}</div>}
    {tab==='概览'&&<><div className="rsi-line"><span>{data.settings.enabled?'已启用':'已停用'} · {data.settings.learningEnabled?'自动学习中':'学习已暂停'}</span><button className="rsi-action" disabled={busy} onClick={()=>perform('settings',{settings:{learningEnabled:!data.settings.learningEnabled}})}>{data.settings.learningEnabled?'暂停学习':'恢复学习'}</button></div><div className="rsi-metrics"><div><span className="rsi-muted">记忆</span><strong>{data.memory.length}</strong></div><div><span className="rsi-muted">技能</span><strong>{data.skills.length}</strong></div><div><span className="rsi-muted">今日学习调用</span><strong>{data.usage.calls}<small className="rsi-muted"> / {data.settings.dailyCallBudget}</small></strong></div></div><div className="rsi-line"><h3>学习记录</h3><button className="rsi-action" disabled={busy||!data.settings.learningEnabled} onClick={()=>perform('learn')}>处理待学习任务</button></div><p className="rsi-muted">Token 用量：{data.usage.totalTokens??'尚未报告'}{data.usage.unknownUsage>0?' · 部分调用未报告用量':''}。失败后可能已有部分资产更新，重试会从已保存的阶段继续。</p><div className="rsi-list">{data.jobs.slice(-20).reverse().map((job:any)=><article className="rsi-card" key={job.id}><div className="rsi-line"><strong>{labels[job.status]??job.status}</strong><time className="rsi-muted">{new Date(job.updated).toLocaleString()}</time></div><div className="rsi-muted">来源会话 {job.sourceSessionId} · 第 {job.turn} 轮</div>{job.error&&<p>{job.error}</p>}</article>)}{!data.jobs.length&&<p className="rsi-empty">完成工作区中的任务后，学习记录会出现在这里。</p>}</div></>}
    {tab==='记忆'&&<MemoryAssets data={data} act={act} busy={busy} open={setDialog}/>}
    {tab==='技能'&&<SkillAssets data={data} act={act} busy={busy} open={setDialog} perform={perform} onImport={()=>{void act('originalSkills').then(list=>{setOriginals(list);setDialog({kind:'import',name:list[0]?.name??''});}).catch(()=>{});}}/>}
    {tab==='设置'&&<div className="rsi-settings"><div className="rsi-grid"><label><input type="checkbox" checked={settings.enabled} onChange={e=>setDraft({...settings,enabled:e.target.checked})}/> 启用资产消费与任务捕获</label><label><input type="checkbox" checked={settings.learningEnabled} onChange={e=>setDraft({...settings,learningEnabled:e.target.checked})}/> 自动学习</label><label><span>新资产语言</span><select value={settings.language} onChange={e=>setDraft({...settings,language:e.target.value})}>{[['zh-CN','简体中文'],['en','English'],['ja','日本語'],['ko','한국어'],['zh-TW','繁體中文']].map(([v,l])=><option key={v} value={v}>{l}</option>)}</select><small className="rsi-muted">不会自动翻译已有资产。</small></label>{[['dailyCallBudget','每日学习调用上限'],['maxTokens','单次输出 Token 上限'],['maxIterations','提炼工具迭代上限'],['everyNConversations','学习间隔（轮）'],['idleSeconds','空闲触发（秒）'],['timeoutMs','单次超时（毫秒）'],['recallMaxChars','召回正文字符上限']].map(([key,label])=><label key={key}><span>{label}</span><input type="number" value={settings[key]} onChange={e=>setDraft({...settings,[key]:Number(e.target.value)})}/></label>)}</div><button className="rsi-action rsi-primary" disabled={busy||!draft} onClick={()=>{void act('settings',{settings:draft}).then(()=>setDraft(undefined)).catch(()=>{});}}>保存设置</button><hr/><h3>资产管理</h3><p className="rsi-muted">清理会删除所选范围内的插件资产和版本，宿主的原始会话日志仍由 dsh 管理。</p>{[data.workspace.id,'global'].map(scope=><div className="rsi-line" key={scope}><span>{scope==='global'?'通用资产':'当前工作区资产'}</span><div><button className="rsi-action" disabled={busy} onClick={()=>void download(scope)}>导出</button> <button className="rsi-action" disabled={busy||data.settings.learningEnabled} onClick={()=>setDialog({kind:'clear',scope,confirm:''})}>清理</button></div></div>)}</div>}
    {dialog&&<div className="rsi-modal" role="dialog" aria-modal="true" aria-label="资产管理"><section className="rsi-dialog"><div className="rsi-line"><h3>{({memory:'纠正记忆',delete:'删除记忆',versions:'技能版本',import:'复制已有技能',promote:'复制为通用技能',clear:'清理资产',rollback:'恢复技能版本',convertSkill:'转换技能语言',convertMemory:'转换记忆语言'} as any)[dialog.kind]}</h3><button className="rsi-action" onClick={()=>setDialog(undefined)}>关闭</button></div>
      {dialog.kind==='memory'&&<><textarea aria-label="记忆正文" value={dialog.content} onChange={e=>setDialog({...dialog,content:e.target.value})}/><button className="rsi-action rsi-primary" disabled={busy} onClick={()=>{void act('editMemory',{scope:dialog.row.scope,id:dialog.row.id,content:dialog.content}).then(()=>setDialog(undefined)).catch(()=>{});}}>保存纠正</button></>}
      {dialog.kind==='delete'&&<><p>{dialog.row.content}</p><button className="rsi-action" disabled={busy} onClick={()=>{void act('deleteMemory',{scope:dialog.row.scope,id:dialog.row.id}).then(()=>setDialog(undefined)).catch(()=>{});}}>确认删除</button></>}
      {dialog.kind==='import'&&<><p>复制正文与本地资源；后续演进写入插件目录。</p><select aria-label="已有技能" value={dialog.name} onChange={e=>setDialog({...dialog,name:e.target.value})}>{originals.map(s=><option key={s.name} value={s.name}>{s.name}</option>)}</select><button className="rsi-action" disabled={busy||!dialog.name} onClick={()=>{void act('importSkill',{name:dialog.name}).then(()=>setDialog(undefined)).catch(()=>{});}}>创建副本</button></>}
      {dialog.kind==='versions'&&dialog.versions.items.map((v:any)=><article key={v.version}><div className="rsi-line"><strong>v{v.version}{v.is_expired?'（已过期）':''}</strong>{v.version!==dialog.skill.version&&<button className="rsi-action" disabled={busy||v.is_expired} onClick={()=>setDialog({...dialog,kind:'rollback',target:v})}>恢复此版本</button>}</div><Markdown>{v.content.replace(/^---\r?\n[\s\S]*?\r?\n---(?:\r?\n|$)/,'').trim()}</Markdown>{dialog.versions.items.find((x:any)=>x.version===v.version-1)&&<details><summary>与前一版本的变更片段</summary><pre>{changed(dialog.versions.items.find((x:any)=>x.version===v.version-1).content,v.content)}</pre></details>}<p className="rsi-muted">资源：{v.manifest.map((f:any)=>f.path).join('、')||'无'}</p></article>)}
      {dialog.kind==='rollback'&&<><p>将 v{dialog.target.version} 的正文和资源保存为一个新版本。</p><pre>{dialog.target.content}</pre><button className="rsi-action" disabled={busy} onClick={()=>{void act('rollback',{scope:dialog.skill.scope,id:dialog.skill.skill_id,version:dialog.target.version}).then(()=>setDialog(undefined)).catch(()=>{});}}>确认恢复</button></>}
      {dialog.kind==='promote'&&<><p>把 {dialog.row.visibleName} 复制为其他工作区也能使用的通用技能。</p><button className="rsi-action" disabled={busy} onClick={()=>{void act('promote',{scope:dialog.row.scope,id:dialog.row.skill_id}).then(()=>setDialog(undefined)).catch(()=>{});}}>确认复制</button></>}
      {['convertSkill','convertMemory'].includes(dialog.kind)&&<><p>将正文转换为设置中的 {data.settings.language}，保留原内容的历史版本。此次转换会使用学习调用预算。</p><button className="rsi-action" disabled={busy} onClick={()=>{void act(dialog.kind,{scope:dialog.row.scope,id:dialog.row.skill_id??dialog.row.id}).then(()=>setDialog(undefined)).catch(()=>{});}}>确认转换</button></>}
      {dialog.kind==='clear'&&<><p>此操作会删除该范围的资产及历史版本。输入“清理”确认。</p><input aria-label="清理确认" value={dialog.confirm} onChange={e=>setDialog({...dialog,confirm:e.target.value})}/><button className="rsi-action" disabled={busy||dialog.confirm!=='清理'} onClick={()=>{void act('clear',{scope:dialog.scope,confirm:dialog.scope}).then(()=>setDialog(undefined)).catch(()=>{});}}>确认清理</button></>}
      {error&&<p className="rsi-error" role="alert">{error}</p>}
    </section></div>}
  </section>;
}
export async function apply(ctx:any) {
  const unmount=await ctx.remote.$mount(remoteContribution);ctx.effect(()=>unmount);
  ctx.effect(()=>ctx.locale.register('rsi',{zh:{title:'自进化'},en:{title:'Self evolution'}}));
  ctx.inject(['remote.rsi'],(child:any)=>child.effect(()=>child.slots.inject('plugins.bundle.config',()=>child.slots.register({name:'plugins.bundle.config',key:'dsh-rsi',locale:'rsi'},()=> <Panel ctx={child}/>))));
}
